---
- hosts: master
  #  become: true
  user: edureka

  tasks:
    - name: check version
      command: kubectl --kubeconfig /root/.kube/admin.conf version

    - name: create deployment
      command: kubectl --kubeconfig /root/.kube/admin.conf apply -f deployment.yml

      args:
        chdir: /opt/k8s

    - name: create service
      command: kubectl --kubeconfig /root/.kube/admin.conf apply -f service.yml

      args:
        chdir: /opt/k8s

    - name: update deployment if pods updated in container repository
      command: kubectl --kubeconfig /root/.kube/admin.conf rollout restart deployment.apps/abc-deploy
